### ISSUE TITLE
submitData is reverting

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/example-app#2]
When attempting to call submitData using MetaMask it reverts for some reason.

**Comment by tjchern** [comment]
error: SOLVER: Error while handling EndRevealPeriod event {"logIndex":0,"transactionIndex":0,"transactionHash":"0xc6f4662eb061156e03a9962d11662a48ac787c195c1f476291406a3167b523f1","blockHash":"0xdcf5165abbec761d6bac57036adc635d1d1bee090b55edd3fdd7029f5322c6a4","blockNumber":1852,"address":"0xc045c7b6b976d24728872d2117073c893d0b09c2","type":"mined","event":"EndRevealPeriod","args":{"taskID":"0xc7fe4001d48e85229349be03cf2936ba2d5339542298e67fdb15b629e089f00f"}}: Error: VM Exception while processing transaction: revert
2019-01-09 21:19:16 [console] info: SOLVER: Revealed correct solution

I encounter this problem now

**Comment by tjchern** [comment]
How to resolve it, when call submitData using metamask, it revert

**Comment by hswick** [comment]
Hmmm, this is a problem with that particular version of truebit-os. Do you mind updating it to the current master branch? We have made a lot of changes since we made this repo.

**Comment by tjchern** [comment]
Yes, I use the master branch, but on the macos

**Comment by hswick** [comment]
Oops, my bad I forgot this repo doesnt use a submodule. Apologies that the master branch contains some breaking changes. I just got done refactoring the filesystem, so I'll have to update this repo as well. Hoping to have everything ready next week.

**Comment by tjchern** [comment]
Hi, do you fix this bug ?
Can you provide the original solidity of secret the hash ?

**Comment by hswick** [comment]
Hi, we havent merged any changes into truebit-os:master. You can follow progress there.

Edit:
I believe this issue is related to https://github.com/TrueBitFoundation/truebit-os/issues/99. Which is a high priority.
